name: 'AWS GitHub Runner Management'
description: 'self-hosted AWS GitHub runners management'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  mode:
    description: 'Mode of operation (start/stop)'
    required: true
    options: ['start', 'stop']
  github-token:
    description: 'GitHub Personal Access Token'
    required: true
  github-token-type:
    description: 'GitHub Token Type'
    required: false
    default: 'legacy'
    options: ['legacy', 'fine-grained']
  github-org-runner:
    description: 'GitHub Organization Runner (true/false)'
    required: false
    default: 'false'
  ec2-image-id:
    description: 'AWS EC2 AMI ID'
    required: true
  ec2-instance-type:
    description: 'EC2 Instance Type'
    required: false
    default: 't2.micro'
  spot-instance:
    description: 'Use Spot Instance'
    required: false
    default: 'false'
  spot-price:
    description: 'Maximum price for Spot Instance'
    required: false
    default: '0.10'
  subnet-id:
    description: 'Subnet ID for EC2 instance'
    required: true
  security-group-id:
    description: 'Security Group ID for EC2 instance'
    required: true
  iam-instance-role:
    description: 'IAM Instance Role name'
    required: false
  aws-resource-tags:
    description: 'JSON formatted AWS resource tags'
    required: false
    default: '[]'

outputs:
  label:
    description: 'Generated runner label'
  ec2-instance-id:
    description: 'EC2 Instance ID of the runner'

runs:
  using: 'docker'
  image: 'Dockerfile'
